import { type NextPage } from "next";
import Head from "next/head";
import AppStats from "../components/LandingPage/AppStats";
import Hero from "../components/LandingPage/Hero";
import NavBar from "../components/LandingPage/NavBar";
import Reviews from "../components/LandingPage/Reviews";
import { useTheme } from "../hooks/useTheme";
import { appRouter } from "../server/trpc/router/_app";
import { createContext } from "../server/trpc/context";

interface IHomeProps {
  registeredUsers: number;
  learnedCards: number;
  numOfQuizes: number;
}

export async function getStaticProps() {
  const trpc = appRouter.createCaller(await createContext());
  const result = await trpc.stats.getAllStats();
  return {
    props: {
      ...result,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 300, // In seconds
  }
}


const Home: NextPage<IHomeProps> = ({
  registeredUsers,
  learnedCards,
  numOfQuizes
}) => {
  const { theme, setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Quizzy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar theme={theme} setTheme={setTheme} />
        <Hero theme={theme} />
        <div className="my-16 bg-base-300 pb-16 pt-24">
          <section className="container mx-auto pb-12 lg:px-40">
            <div className="flex flex-col items-center gap-12 lg:flex-row">
              <div className="lg:w-1/2">
                <h3 className="text-4xl font-bold">Memorize faster</h3>
                <p className="pt-4">
                  Research shows that testing yourself with flashcards is more
                  effective than rereading your notes. From math to medicine to
                  modern languages, Quizzy is used by students in over 100
                  different subjects.
                </p>
              </div>
              <div className="stack mt-4 lg:mt-0 lg:w-1/2">
                <div>
                  <div className="card h-72 w-full rotate-3 items-center bg-base-100 text-base-content shadow-xl">
                    <div className="card-body grid items-center text-xl font-bold">
                      What is the largest city in the world?
                    </div>
                  </div>
                </div>
                <div>
                  <div className="card h-72 w-full -rotate-6 bg-primary shadow-sm" />
                </div>
                <div className="card h-72 w-full rotate-12 bg-secondary shadow-sm" />
              </div>
            </div>
          </section>
        </div>

        <section className="container mx-auto py-12 leading-relaxed lg:px-40">
          <h2 className="text-center text-4xl font-bold">
            Why Use Flashcards for Learning?
          </h2>
          <p className="pt-2">
            Flashcards are a powerful tool for learning and retaining
            information. Here are some reasons why students should consider
            using flashcards for studying:
          </p>
          <ul className="grid grid-cols-1 gap-4 pt-4 lg:grid-cols-3">
            <li className="relative pl-4">
              <span className="absolute -left-2 top-1 h-4 w-4 rounded-full bg-secondary" />
              <h5 className="text-xl font-bold"> Active Learning</h5> Flashcards
              encourage active learning, where students engage with the material
              rather than passively reading or listening. By creating and using
              flashcards, students actively process and review the information,
              leading to better understanding and retention.
            </li>
            <li className="relative pl-4">
              <span className="absolute -left-2 top-1 h-4 w-4 rounded-full bg-secondary" />
              <h5 className="text-xl font-bold">Proven</h5> Flashcards are a
              proven way to improve your learning, they work by exercising your
              active recall. Active recall is the process of actively retrieving
              information from your memory, rather than simply reading and
              re-reading the material.
            </li>
            <li className="relative pl-4">
              <span className="absolute -left-2 top-1 h-4 w-4 rounded-full bg-secondary" />
              <h5 className="text-xl font-bold"> Spaced Repetition</h5>
              Flashcards are ideal for spaced repetition, a technique that
              involves reviewing material at intervals over time. By spacing out
              the review sessions, students are more likely to retain the
              information over the long-term.
            </li>
            <li className="relative pl-4">
              <span className="absolute -left-2 top-1 h-4 w-4 rounded-full bg-secondary" />{" "}
              <h5 className="text-xl font-bold">Customizable</h5> Flashcards can
              be customized to suit individual needs. Students can create
              flashcards for specific topics or concepts, and add images or
              visual aids to make the information more memorable.
            </li>
            <li className="relative pl-4">
              <span className="absolute -left-2 top-1 h-4 w-4 rounded-full bg-secondary" />
              <h5 className="text-xl font-bold">Efficient Studying</h5>
              Flashcards are a quick and efficient way to study, especially when
              time is limited. Students can review flashcards while waiting for
              a bus, standing in line, or during short breaks in between classes
              or studying.
            </li>
            <li className="relative pl-4">
              <span className="absolute -left-2 top-1 h-4 w-4 rounded-full bg-secondary" />
              <h5 className="text-xl font-bold">Engaging and Fun</h5> Flashcards
              can be a fun and engaging way to study, especially when used with
              others. Students can quiz each other on the material or play games
              that involve using the flashcards.
            </li>
          </ul>
          <p className="pt-4">
            Overall, flashcards are a versatile and useful tool for students of
            all ages and backgrounds. They can help students learn and retain
            information more effectively and make studying more enjoyable.
          </p>
        </section>
        <AppStats
          registeredUsers={registeredUsers}
          learnedCards={learnedCards}
          numOfQuizes={numOfQuizes}

        />
        <Reviews />
      </main>
    </>
  );
};


export default Home;
