import { useAutoAnimate } from "@formkit/auto-animate/react";
import { type NextPage } from "next";
import Head from "next/head";
import { MainNavBar } from "../../components/MainNavBar";
import Modal from "../../components/Modal";
import Sidebar from "../../components/Sidebar";
import { requireAuth } from "../../middleware/requireAuth";
import { useTabStore } from "../../store/tabStore";

const Home: NextPage = () => {
  const [animationParent] = useAutoAnimate<HTMLDivElement>();
  const { content } = useTabStore((state) => state.activeTab);

  return (
    <>
      <Head>
        <title>Quizzy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar>
        <main ref={animationParent} className="container flex flex-col gap-2">
          <MainNavBar />
          {content}
        </main>
      </Sidebar>
      <Modal />
    </>
  );
};

export const getServerSideProps = requireAuth(async () => {
  return {
    props: {},
  };
});

export default Home;
